---
name: NoFapBot binary Release

on:
  push:
    branches: [ "master" ]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Pull master branch
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python3.8 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then python3.8 -m pip install -r requirements.txt; fi
    - name: Install nuitka package
      run: |
        python3.8 -m pip install nuitka
    - name: Create one-file binary for no_fap.py
      run: |
        python3.8 -m nuitka --onefile --include-data-dir=./storage=storage --follow-imports no_fap.py
    - name: "Create auto-Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          no_fap.bin
